// productData.js
const initialProducts = [
    { name: 'T-Shirt', price: 21.07, stock: 33, category: 'Health' },
    { name: 'Desk Lamp', price: 3603.06, stock: 9, category: 'Accessories' },
    { name: 'Running Shoes', price: 3694.12, stock: 39, category: 'Furniture' },
    { name: 'Hand Sanitizer', price: 4537.04, stock: 21, category: 'Accessories' },
    { name: 'Wireless Charger', price: 4637.06, stock: 8, category: 'Kitchen' },
    { name: 'Notebook', price: 7822.38, stock: 49, category: 'Accessories' },
    { name: 'Laptop Stand', price: 763.37, stock: 10, category: 'Kitchen' },
    { name: 'Backpack', price: 7330.22, stock: 14, category: 'Footwear' },
    { name: 'Notebook', price: 5763.29, stock: 39, category: 'Footwear' },
    { name: 'Keyboard', price: 5085.6, stock: 15, category: 'Clothing' },
    { name: 'T-Shirt', price: 94.96, stock: 17, category: 'Electronics' },
    { name: 'LED Monitor', price: 4653.72, stock: 11, category: 'Accessories' },
    { name: 'Keyboard', price: 60.17, stock: 21, category: 'Clothing' },
    { name: 'Running Shoes', price: 6416.86, stock: 36, category: 'Kitchen' },
    { name: 'Notebook', price: 5752.66, stock: 27, category: 'Kitchen' },
    { name: 'Power Bank', price: 9880.6, stock: 27, category: 'Kitchen' },
    { name: 'Coffee Mug', price: 7311.39, stock: 19, category: 'Furniture' },
    { name: 'Pen', price: 4617.15, stock: 7, category: 'Clothing' },
    { name: 'Desk Organizer', price: 8713.95, stock: 43, category: 'Footwear' },
    { name: 'Wireless Charger', price: 7935.05, stock: 21, category: 'Furniture' },
    { name: 'Desk Lamp', price: 1476.14, stock: 0, category: 'Kitchen' },
    { name: 'Hand Sanitizer', price: 284.97, stock: 40, category: 'Accessories' },
    { name: 'Water Bottle', price: 7245.81, stock: 43, category: 'Health' },
    { name: 'Notebook', price: 6518.49, stock: 35, category: 'Kitchen' },
    { name: 'Bluetooth Speaker', price: 5786.14, stock: 0, category: 'Clothing' },
    { name: 'Running Shoes', price: 2367.14, stock: 29, category: 'Accessories' },
    { name: 'Sneakers', price: 8773.33, stock: 32, category: 'Electronics' },
    { name: 'Running Shoes', price: 1653.79, stock: 16, category: 'Clothing' },
    { name: 'Wireless Mouse', price: 8497.19, stock: 11, category: 'Footwear' },
    { name: 'Water Bottle', price: 5326.36, stock: 21, category: 'Stationery' },
    { name: 'Desk Organizer', price: 5198.14, stock: 9, category: 'Health' },
    { name: 'Pen', price: 7929.55, stock: 29, category: 'Accessories' },
    { name: 'Bluetooth Speaker', price: 5365.02, stock: 21, category: 'Stationery' },
    { name: 'Bluetooth Speaker', price: 6101.48, stock: 15, category: 'Stationery' },
    { name: 'T-Shirt', price: 7271.53, stock: 18, category: 'Electronics' },
    { name: 'Bluetooth Speaker', price: 2210.46, stock: 5, category: 'Health' },
    { name: 'Desk Lamp', price: 9275.3, stock: 43, category: 'Stationery' },
    { name: 'Power Bank', price: 8383.19, stock: 48, category: 'Stationery' },
    { name: 'Sunglasses', price: 6511.27, stock: 47, category: 'Health' },
    { name: 'LED Monitor', price: 7072.12, stock: 37, category: 'Furniture' },
    { name: 'Notebook', price: 7960.08, stock: 33, category: 'Furniture' },
    { name: 'Water Bottle', price: 2152.65, stock: 27, category: 'Clothing' },
    { name: 'Power Bank', price: 8527.04, stock: 49, category: 'Electronics' },
    { name: 'Bluetooth Speaker', price: 1383.17, stock: 8, category: 'Electronics' },
    { name: 'Pen', price: 4118.45, stock: 34, category: 'Clothing' },
    { name: 'Notebook', price: 8395.96, stock: 46, category: 'Kitchen' },
    { name: 'Wireless Charger', price: 9568.28, stock: 36, category: 'Furniture' },
    { name: 'Wireless Mouse', price: 2613.58, stock: 24, category: 'Clothing' },
    { name: 'Sunglasses', price: 3865.05, stock: 30, category: 'Furniture' },
    { name: 'Sunglasses', price: 2344.88, stock: 10, category: 'Stationery' },
    { name: 'Desk Lamp', price: 7246.98, stock: 4, category: 'Electronics' },
    { name: 'LED Monitor', price: 6236.88, stock: 20, category: 'Health' },
    { name: 'Wireless Mouse', price: 8880.16, stock: 47, category: 'Footwear' },
    { name: 'Pen', price: 9670.3, stock: 37, category: 'Accessories' },
    { name: 'Wireless Charger', price: 1868.89, stock: 34, category: 'Stationery' },
    { name: 'Notebook', price: 7497.8, stock: 7, category: 'Footwear' },
    { name: 'Keyboard', price: 6618.76, stock: 27, category: 'Footwear' },
    { name: 'Wireless Mouse', price: 8661.58, stock: 25, category: 'Electronics' },
    { name: 'Bluetooth Speaker', price: 1325.29, stock: 30, category: 'Kitchen' },
    { name: 'Keyboard', price: 5620.08, stock: 31, category: 'Footwear' },
    { name: 'Laptop Stand', price: 2698.85, stock: 5, category: 'Furniture' },
    { name: 'Laptop Stand', price: 5991.49, stock: 32, category: 'Stationery' },
    { name: 'Bluetooth Speaker', price: 1232.93, stock: 21, category: 'Furniture' },
    { name: 'Running Shoes', price: 5438.44, stock: 25, category: 'Footwear' },
    { name: 'Keyboard', price: 4269.13, stock: 48, category: 'Furniture' },
    { name: 'Desk Lamp', price: 6858.04, stock: 45, category: 'Footwear' },
    { name: 'Wireless Mouse', price: 8225.64, stock: 41, category: 'Electronics' },
    { name: 'Running Shoes', price: 1345.92, stock: 7, category: 'Furniture' },
    { name: 'Water Bottle', price: 4899.01, stock: 11, category: 'Furniture' },
    { name: 'Power Bank', price: 2520.39, stock: 50, category: 'Health' },
    { name: 'Water Bottle', price: 8703.49, stock: 34, category: 'Accessories' },
    { name: 'Power Bank', price: 1626.32, stock: 7, category: 'Kitchen' },
    { name: 'Desk Lamp', price: 7060.42, stock: 15, category: 'Clothing' },
    { name: 'Backpack', price: 3455.08, stock: 10, category: 'Electronics' },
    { name: 'Desk Organizer', price: 9064.44, stock: 17, category: 'Clothing' },
    { name: 'Water Bottle', price: 7572.35, stock: 12, category: 'Health' },
    { name: 'Sneakers', price: 201.15, stock: 31, category: 'Furniture' },
    { name: 'Bluetooth Speaker', price: 7458.39, stock: 27, category: 'Furniture' },
    { name: 'Bluetooth Speaker', price: 8786.93, stock: 43, category: 'Footwear' },
    { name: 'Power Bank', price: 7071.28, stock: 12, category: 'Stationery' },
    { name: 'Hand Sanitizer', price: 8251.69, stock: 33, category: 'Accessories' },
    { name: 'Water Bottle', price: 2749.3, stock: 3, category: 'Health' },
    { name: 'Desk Organizer', price: 1091.44, stock: 42, category: 'Accessories' },
    { name: 'Notebook', price: 5423.58, stock: 1, category: 'Accessories' },
    { name: 'T-Shirt', price: 4789.61, stock: 45, category: 'Kitchen' },
    { name: 'T-Shirt', price: 2260.38, stock: 43, category: 'Electronics' },
    { name: 'LED Monitor', price: 9523.63, stock: 24, category: 'Furniture' },
    { name: 'T-Shirt', price: 5803.16, stock: 4, category: 'Clothing' },
    { name: 'Desk Lamp', price: 8148.6, stock: 39, category: 'Furniture' },
    { name: 'Keyboard', price: 4704.36, stock: 39, category: 'Health' },
    { name: 'Pen', price: 6959.39, stock: 12, category: 'Footwear' },
    { name: 'Notebook', price: 4613.81, stock: 45, category: 'Health' },
    { name: 'Sneakers', price: 2824.38, stock: 17, category: 'Stationery' },
    { name: 'Power Bank', price: 4432.92, stock: 45, category: 'Electronics' },
    { name: 'T-Shirt', price: 5329.01, stock: 0, category: 'Stationery' },
    { name: 'Pen', price: 8179.51, stock: 49, category: 'Furniture' },
    { name: 'Phone Case', price: 5326.01, stock: 11, category: 'Accessories' },
    { name: 'Running Shoes', price: 9194.83, stock: 3, category: 'Electronics' },
    { name: 'Backpack', price: 6993.85, stock: 21, category: 'Clothing' },
    { name: 'Running Shoes', price: 3600.14, stock: 11, category: 'Clothing' },
    { name: 'Backpack', price: 274.11, stock: 10, category: 'Health' },
    { name: 'LED Monitor', price: 5123.67, stock: 31, category: 'Health' },
    { name: 'Keyboard', price: 8190.34, stock: 8, category: 'Electronics' },
    { name: 'Pen', price: 6627.21, stock: 2, category: 'Kitchen' },
    { name: 'LED Monitor', price: 884.22, stock: 16, category: 'Health' },
    { name: 'Running Shoes', price: 5390.55, stock: 1, category: 'Furniture' },
    { name: 'Phone Case', price: 644.87, stock: 42, category: 'Electronics' },
    { name: 'Running Shoes', price: 2451.15, stock: 18, category: 'Accessories' },
    { name: 'LED Monitor', price: 3624.39, stock: 7, category: 'Stationery' },
    { name: 'Water Bottle', price: 1111.47, stock: 48, category: 'Accessories' },
    { name: 'Sunglasses', price: 380.9, stock: 16, category: 'Electronics' },
    { name: 'Keyboard', price: 3637.39, stock: 2, category: 'Furniture' },
    { name: 'Sunglasses', price: 7733.73, stock: 34, category: 'Accessories' },
    { name: 'Sneakers', price: 233.24, stock: 27, category: 'Accessories' },
    { name: 'Running Shoes', price: 7478.25, stock: 29, category: 'Health' },
    { name: 'Desk Lamp', price: 7398.7, stock: 8, category: 'Accessories' },
    { name: 'Bluetooth Speaker', price: 7222.87, stock: 32, category: 'Clothing' },
    { name: 'Coffee Mug', price: 2826.08, stock: 20, category: 'Stationery' },
    { name: 'Sneakers', price: 2378.23, stock: 36, category: 'Footwear' },
    { name: 'T-Shirt', price: 9773.27, stock: 21, category: 'Accessories' },
    { name: 'Backpack', price: 2844.9, stock: 41, category: 'Kitchen' },
    { name: 'Sneakers', price: 9114.76, stock: 14, category: 'Kitchen' },
    { name: 'Laptop Stand', price: 2802.9, stock: 40, category: 'Electronics' },
    { name: 'Coffee Mug', price: 2295.26, stock: 6, category: 'Clothing' },
    { name: 'Hand Sanitizer', price: 1427.19, stock: 13, category: 'Kitchen' },
    { name: 'Sunglasses', price: 7157.3, stock: 31, category: 'Health' },
    { name: 'Hand Sanitizer', price: 4530.42, stock: 36, category: 'Kitchen' },
    { name: 'Wireless Mouse', price: 6029.32, stock: 30, category: 'Footwear' },
    { name: 'Coffee Mug', price: 4413.28, stock: 21, category: 'Accessories' },
    { name: 'T-Shirt', price: 7248.53, stock: 41, category: 'Electronics' },
    { name: 'Desk Organizer', price: 4534.4, stock: 42, category: 'Electronics' },
    { name: 'Backpack', price: 5853.45, stock: 12, category: 'Electronics' },
    { name: 'Coffee Mug', price: 1265.93, stock: 0, category: 'Accessories' },
    { name: 'Hand Sanitizer', price: 4403.6, stock: 31, category: 'Stationery' },
    { name: 'T-Shirt', price: 6355.7, stock: 26, category: 'Stationery' },
    { name: 'T-Shirt', price: 1175.4, stock: 35, category: 'Stationery' },
    { name: 'Laptop Stand', price: 958.74, stock: 13, category: 'Health' },
    { name: 'Desk Organizer', price: 6894, stock: 39, category: 'Electronics' },
    { name: 'Backpack', price: 2382.49, stock: 34, category: 'Kitchen' },
    { name: 'Power Bank', price: 2040.9, stock: 31, category: 'Accessories' },
    { name: 'Desk Organizer', price: 1871.23, stock: 37, category: 'Kitchen' },
    { name: 'Desk Organizer', price: 9019.72, stock: 26, category: 'Stationery' },
    { name: 'Laptop Stand', price: 8084.03, stock: 39, category: 'Stationery' },
    { name: 'Backpack', price: 3220.77, stock: 14, category: 'Clothing' },
    { name: 'Backpack', price: 7732.92, stock: 33, category: 'Stationery' },
    { name: 'Power Bank', price: 4188.61, stock: 41, category: 'Clothing' },
    { name: 'Desk Lamp', price: 6454.29, stock: 11, category: 'Clothing' },
    { name: 'Laptop Stand', price: 1192.96, stock: 33, category: 'Stationery' },
    { name: 'Desk Lamp', price: 9302.12, stock: 46, category: 'Kitchen' },
    { name: 'Sunglasses', price: 9225.6, stock: 22, category: 'Footwear' },
    { name: 'Desk Lamp', price: 8629.28, stock: 5, category: 'Electronics' },
    { name: 'Backpack', price: 9745.03, stock: 26, category: 'Accessories' },
    { name: 'Running Shoes', price: 9372.29, stock: 45, category: 'Stationery' },
    { name: 'Backpack', price: 9157.25, stock: 35, category: 'Stationery' },
    { name: 'Phone Case', price: 6370.49, stock: 38, category: 'Footwear' },
    { name: 'Notebook', price: 1377.17, stock: 12, category: 'Health' },
    { name: 'Notebook', price: 9791.23, stock: 3, category: 'Clothing' },
    { name: 'Laptop Stand', price: 3290.11, stock: 8, category: 'Clothing' },
    { name: 'Coffee Mug', price: 3344.38, stock: 41, category: 'Health' },
    { name: 'Sneakers', price: 1254.97, stock: 14, category: 'Electronics' },
    { name: 'Pen', price: 29.19, stock: 34, category: 'Electronics' },
    { name: 'LED Monitor', price: 2428.11, stock: 32, category: 'Clothing' },
    { name: 'Pen', price: 9585.52, stock: 36, category: 'Furniture' },
    { name: 'Pen', price: 4396.31, stock: 44, category: 'Furniture' },
    { name: 'Desk Lamp', price: 4831.35, stock: 13, category: 'Furniture' },
    { name: 'Bluetooth Speaker', price: 856.32, stock: 17, category: 'Stationery' },
    { name: 'Wireless Mouse', price: 345.01, stock: 13, category: 'Stationery' },
    { name: 'Phone Case', price: 5161.39, stock: 50, category: 'Furniture' },
    { name: 'Keyboard', price: 507.23, stock: 49, category: 'Electronics' },
    { name: 'LED Monitor', price: 7678.57, stock: 45, category: 'Health' },
    { name: 'Bluetooth Speaker', price: 5284.31, stock: 10, category: 'Accessories' },
    { name: 'Power Bank', price: 993.26, stock: 16, category: 'Clothing' },
    { name: 'Keyboard', price: 7750.34, stock: 43, category: 'Footwear' },
    { name: 'Wireless Mouse', price: 1423.18, stock: 10, category: 'Health' },
    { name: 'Desk Lamp', price: 3530, stock: 28, category: 'Electronics' },
    { name: 'Pen', price: 9182.54, stock: 1, category: 'Accessories' },
    { name: 'Hand Sanitizer', price: 4767.35, stock: 45, category: 'Electronics' },
    { name: 'Desk Organizer', price: 6645.86, stock: 26, category: 'Stationery' },
    { name: 'Notebook', price: 9963.06, stock: 4, category: 'Kitchen' },
    { name: 'Hand Sanitizer', price: 3543.27, stock: 35, category: 'Electronics' },
    { name: 'Desk Organizer', price: 4833.12, stock: 16, category: 'Accessories' },
    { name: 'Power Bank', price: 8619.4, stock: 3, category: 'Footwear' },
    { name: 'Pen', price: 936.5, stock: 17, category: 'Footwear' },
    { name: 'Backpack', price: 1724.3, stock: 8, category: 'Clothing' },
    { name: 'Coffee Mug', price: 226.97, stock: 3, category: 'Kitchen' },
    { name: 'Coffee Mug', price: 7853.76, stock: 31, category: 'Health' },
    { name: 'Water Bottle', price: 9534.54, stock: 35, category: 'Footwear' },
    { name: 'Keyboard', price: 1182.21, stock: 48, category: 'Furniture' },
    { name: 'Notebook', price: 7545.48, stock: 49, category: 'Clothing' },
    { name: 'Hand Sanitizer', price: 5121.4, stock: 31, category: 'Kitchen' },
    { name: 'Hand Sanitizer', price: 8713, stock: 23, category: 'Kitchen' },
    { name: 'Phone Case', price: 745.44, stock: 42, category: 'Health' },
    { name: 'Power Bank', price: 1991.03, stock: 46, category: 'Health' },
    { name: 'Bluetooth Speaker', price: 7530.41, stock: 4, category: 'Kitchen' },
    { name: 'Power Bank', price: 3391.19, stock: 4, category: 'Electronics' },
    { name: 'Backpack', price: 3983.3, stock: 3, category: 'Clothing' },
    { name: 'Running Shoes', price: 1886.46, stock: 32, category: 'Clothing' },
    { name: 'Pen', price: 4688.9, stock: 38, category: 'Footwear' },
    { name: 'Backpack', price: 2801.77, stock: 18, category: 'Electronics' },
    { name: 'Wireless Charger', price: 7712.1, stock: 38, category: 'Stationery' },
];

module.exports = initialProducts;